version: '3'

services:
        db:
                image: mysql:5.7
                volumes:
                        - data:/var/lib/mysql
                restart:
                        always
                environment:
                        MYSQL_ROOT_PASSWORD: password
                        MYSQL_USER: wpuser
                        MYSQL_DATABASE: wordpress
                        MYSQL_PASSWORD: wordpress

        wordpress:
                depends_on:
                        - db
                image: wordpress:latest
                ports:
                        - 80:80
                volumes:
                        - wordpress:/var/www/html
                environment:
                        WORDPRESS_DB_HOST: db
                        WORDPRESS_DB_NAME: wordpress
                        WORDPRESS_DB_USER: wpuser
                        WORDPRESS_DB_PASSWORD: wordpress
                        SITE_URL: ${SITE_URL}
                        WORDPRESS_CONFIG_EXTRA: |
                                define( 'WP_HOME', '${SITE_URL}');
                                define( 'WP_SITEURL', '${SITE_URL}');

volumes:
        data:
        wordpress:

